from pwn import *

commands = [
    'INSERT Students_ind ("Mykola", "FB-31", "19", "Kyiv");',
    'INSERT Students_ind ("Elizaveta", "FB-31", "19", "Kyiv");',
    'INSERT Students_ind ("Anna", "FB-31", "21", "Mariupol");',
    'INSERT Students_ind ("Igor", "FB-31", "20", "Lviv");',
    'INSERT Students_ind ("Victoria", "FB-31", "18", "Odesa");',
    'INSERT Students_ind ("Mykola", "FB-32", "22", "Kyiv");',
    'INSERT Students_ind ("Elizaveta", "FB-32", "20", "Mariupol");',
    'INSERT Students_ind ("Anna", "FB-32", "21", "Odesa");',
    'INSERT Students_ind ("Igor", "FB-32", "18", "Donetsk");',
    'INSERT Students_ind ("Victoria", "FB-32", "19", "Lviv");',
    'INSERT Students_ind ("Mykola", "FB-33", "18", "Mariupol");',
    'INSERT Students_ind ("Elizaveta", "FB-33", "21", "Lviv");',
    'INSERT Students_ind ("Anna", "FB-33", "19", "Kyiv");',
    'INSERT Students_ind ("Igor", "FB-33", "22", "Odesa");',
    'INSERT Students_ind ("Victoria", "FB-33", "20", "Donetsk");',
    'INSERT Students_ind ("Mykola", "FB-21", "19", "Odesa");',
    'INSERT Students_ind ("Elizaveta", "FB-21", "21", "Lviv");',
    'INSERT Students_ind ("Anna", "FB-21", "22", "Mariupol");',
    'INSERT Students_ind ("Igor", "FB-21", "20", "Kyiv");',
    'INSERT Students_ind ("Victoria", "FB-21", "22", "Donetsk");',
    'INSERT Students_ind ("Mykola", "FB-22", "18", "Mariupol");',
    'INSERT Students_ind ("Elizaveta", "FB-22", "21", "Kyiv");',
    'INSERT Students_ind ("Anna", "FB-22", "19", "Lviv");',
    'INSERT Students_ind ("Igor", "FB-22", "22", "Odesa");',
    'INSERT Students_ind ("Elizaveta", "FB-32", "18", "Lviv");',
    'INSERT Students_ind ("Anna", "FB-32", "20", "Kyiv");',
    'INSERT Students_ind ("Igor", "FB-32", "19", "Odesa");',
    'INSERT Students_ind ("Victoria", "FB-32", "22", "Mariupol");',
    'INSERT Students_ind ("Mykola", "FB-33", "19", "Kyiv");',
    'INSERT Students_ind ("Elizaveta", "FB-33", "22", "Lviv");',
    'INSERT Students_ind ("Anna", "FB-33", "20", "Odesa");',
    'INSERT Students_ind ("Igor", "FB-33", "18", "Donetsk");',
    'INSERT Students_ind ("Victoria", "FB-33", "21", "Mariupol");',
    'INSERT Students_ind ("Mykola", "FB-21", "20", "Odesa");',
    'INSERT Students_ind ("Elizaveta", "FB-21", "22", "Mariupol");',
    'INSERT Students_ind ("Anna", "FB-21", "18", "Kyiv");',
    'INSERT Students_ind ("Igor", "FB-21", "19", "Lviv");',
    'INSERT Students_ind ("Victoria", "FB-21", "20", "Donetsk");',
    'INSERT Students_ind ("Mykola", "FB-22", "21", "Kyiv");',
    'INSERT Students_ind ("Elizaveta", "FB-22", "19", "Lviv");',
    'INSERT Students_ind ("Anna", "FB-22", "20", "Mariupol");',
    'INSERT Students_ind ("Igor", "FB-22", "22", "Odesa");',
    'INSERT Students_ind ("Victoria", "FB-22", "18", "Donetsk");',
    'INSERT Students_ind ("Mykola", "FB-23", "21", "Odesa");',
    'INSERT Students_ind ("Elizaveta", "FB-23", "19", "Mariupol");',
    'INSERT Students_ind ("Anna", "FB-23", "20", "Lviv");',
    'INSERT Students_ind ("Igor", "FB-23", "18", "Kyiv");',
    'INSERT Students_ind ("Victoria", "FB-23", "21", "Donetsk");',
    'INSERT Students_ind ("Mykola", "FB-24", "22", "Mariupol");',
    'INSERT Students_ind ("Elizaveta", "FB-24", "20", "Kyiv");',
    'INSERT Students_ind ("Anna", "FB-24", "21", "Odesa");',
    'INSERT Students_ind ("Igor", "FB-24", "19", "Lviv");',
    'INSERT Students_ind ("Victoria", "FB-22", "20", "Donetsk");',
    'INSERT Students_ind ("Mykola", "FB-23", "20", "Kyiv");',
    'INSERT Students_ind ("Elizaveta", "FB-23", "22", "Odesa");',
    'INSERT Students_ind ("Anna", "FB-23", "18", "Mariupol");',
    'INSERT Students_ind ("Igor", "FB-23", "21", "Lviv");',
    'INSERT Students_ind ("Victoria", "FB-23", "19", "Donetsk");',
    'INSERT Students_ind ("Mykola", "FB-24", "22", "Lviv");',
    'INSERT Students_ind ("Elizaveta", "FB-24", "19", "Kyiv");',
    'INSERT Students_ind ("Anna", "FB-24", "21", "Mariupol");',
    'INSERT Students_ind ("Igor", "FB-24", "20", "Odesa");',
    'INSERT Students_ind ("Victoria", "FB-24", "18", "Donetsk");',
    'INSERT Students_ind ("Mykola", "FB-25", "22", "Kyiv");',
    'INSERT Students_ind ("Elizaveta", "FB-25", "20", "Mariupol");',
    'INSERT Students_ind ("Anna", "FB-25", "19", "Lviv");',
    'INSERT Students_ind ("Igor", "FB-25", "21", "Odesa");',
    'INSERT Students_ind ("Victoria", "FB-25", "18", "Kyiv");',
    'INSERT Students_ind ("Mykola", "FB-11", "19", "Donetsk");',
    'INSERT Students_ind ("Elizaveta", "FB-11", "22", "Kyiv");',
    'INSERT Students_ind ("Anna", "FB-11", "18", "Mariupol");',
    'INSERT Students_ind ("Igor", "FB-11", "20", "Lviv");',
    'INSERT Students_ind ("Victoria", "FB-11", "19", "Odesa");',
    'INSERT Students_ind ("Mykola", "FB-12", "21", "Mariupol");',
    'INSERT Students_ind ("Elizaveta", "FB-12", "19", "Kyiv");',
    'INSERT Students_ind ("Anna", "FB-12", "20", "Lviv");',
    'INSERT Students_ind ("Igor", "FB-12", "22", "Odesa");',
    'INSERT Students_ind ("Victoria", "FB-12", "21", "Donetsk");',
    'INSERT Students_ind ("Mykola", "FB-13", "20", "Odesa");',
    'INSERT Students_ind ("Elizaveta", "FB-13", "21", "Mariupol");',
    'INSERT Students_ind ("Anna", "FB-13", "18", "Kyiv");',
    'INSERT Students_ind ("Igor", "FB-13", "22", "Lviv");',
    'INSERT Students_ind ("Victoria", "FB-13", "19", "Donetsk");',
    'INSERT Students_ind ("Mykola", "FB-14", "22", "Kyiv");',
    'INSERT Students_ind ("Elizaveta", "FB-14", "19", "Odesa");',
    'INSERT Students_ind ("Anna", "FB-14", "20", "Mariupol");',
    'INSERT Students_ind ("Igor", "FB-14", "18", "Lviv");',
    'INSERT Students_ind ("Victoria", "FB-14", "22", "Donetsk");',
    'INSERT Students_ind ("Mykola", "FB-15", "21", "Lviv");',
    'INSERT Students_ind ("Elizaveta", "FB-15", "22", "Odesa");',
    'INSERT Students_ind ("Anna", "FB-15", "19", "Kyiv");',
    'INSERT Students_ind ("Igor", "FB-15", "20", "Mariupol");',
    'INSERT Students_ind ("Victoria", "FB-15", "18", "Donetsk");',
]

p = process('./aaf_lab.py')
p.interactive() 

for com in commands:
    p.recvuntil("Enter your choice: ")  # Ensure the first prompt is reached
    p.sendline("1")  # Choose option 1 (insert command)
    
    p.recvuntil("> ")  # Wait for the next prompt after choosing option
    p.sendline(com)  # Send the SQL command
    
    p.recvuntil("... ")  # Wait for the next prompt after the command
    p.sendline("")  # Send enter to finalize the command

p.close()
